dataset:
  type: multihead
  root_path: data/multihead/processed_train  # Path to save processed dataset
  xyz_path:
    - data/multihead/train/xyz1         # Path to the directory containing .XYZ files
    - data/multihead/train/xyz2
    - data/multihead/train/xyz3
  xanes_path:
    - data/multihead/train/xanes1     # Path to the directory containing XANES files
    - data/multihead/train/xanes2
    - data/multihead/train/xanes3
  params:
    preload: True                    # Preload dataset into RAM if True; otherwise load on-the-fly
    fourier: True                    # Fourier transformation (default: False)
#    gaussian: True                   # Gaussian transformation (default: False)

descriptors:
  - type: wacsf
#    params:
#      r_min: 1.0
#      r_max: 6.0
#      n_g2: 16
#      n_g4: 32

model:
  type: mh_mlp
  params:
    hidden_size: 512
    head_hidden_size: 512
    dropout: 0.2
    num_hidden_layers: 3
    head_num_hidden_layers: 2
    shrink_rate: 1.0
    head_shrink_rate: 1.0
    activation: silu
  weights:
    kernel: xavier_uniform
    bias: zeros
    seed: 2025

hyperparams:
  epochs: 100
  batch_size: 4
#  lr: 0.001
#  optimizer: Adam
#  seed: 2021
#  loss: mse
#  loss_reg: None # L1 L2
#  loss_lambda: 0.0001

kfold: False
#kfold_params:
#  n_splits: 3
#  n_repeats: 1
#  seed: 2021

bootstrap: False
#bootstrap_params:
#  n_boot: 3
#  n_size: 1.0
#  weight_seed: [97, 39, 22]

ensemble: False
#ensemble_params:
#  n_ens: 3
#  weight_seed: [97, 39, 22]

lr_scheduler: False
#scheduler_params:
#  type: step
#  step_size: 10
#  gamma: 0.5