dataset:
  type: envembed
  root_path: .github/workflows/data/fe/processed_train  # Path to save processed dataset
  xyz_path: .github/workflows/data/fe/xyz_train         # Path to the directory containing .XYZ files
  xanes_path: .github/workflows/data/fe/xanes_train     # Path to the directory containing XANES files
  params:
    preload: True                    # Preload dataset into RAM if True; otherwise load on-the-fly
    gaussian: True
    widths_eV: [0.5, 1.0, 2.0, 4.0]
    basis_stride: 4                  # Value must be consistent with hyperparams/basis_stride


descriptors:
  - type: mace
    params:
      invariants_only: True
      num_layers: 2
      absorber_atom_only: False
#  - type: wacsf
#    params:
#      absorber_atom_only: False
#      r_min: 1.0
#      r_max: 6.0
#      n_g2: 16
#      n_g4: 32

model:
  type: envembed
  params:
      n_shells: 4
      max_radius_angs: 7.0
      init_width: 0.8
      use_gating: True
      head_hidden: 256
      head_depth: 3
      dropout: 0.1

hyperparams:
  batch_size: 4
  epochs: 10
  n_earlystop: 100
  lr: 0.0002
  optimizer: AdamW
  basis_stride: 4
  loss: specplus
  loss_alpha: 0.65
  loss_beta: 0.35
  loss_gamma: 0.25
  loss_huber_delta: 0.01
  widths_eV: [0.5, 1.0, 2.0, 4.0]
  seed: 2021

kfold: False
#kfold_params:
#  n_splits: 3
#  n_repeats: 1
#  seed: 2021

bootstrap: False
#bootstrap_params:
#  n_boot: 3
#  n_size: 1.0
#  weight_seed: [97, 39, 22]

ensemble: False
#ensemble_params:
#  n_ens: 3
#  weight_seed: [97, 39, 22]

lr_scheduler: False
#scheduler_params:
#  type: step
#  step_size: 10
#  gamma: 0.5