seed: 2025
device: cuda

datasource:
  datasource_type: xyzspec
  xyz_path: .github/workflows/data/fe/xyz_train
  xanes_path: .github/workflows/data/fe/xanes_train

dataset:
  dataset_type: xanesx
  root: .github/workflows/data/fe/processed_train
  preload: True                    # Preload dataset into RAM if True; otherwise load on-the-fly
  params:
    fourier: False
    fourier_concat: False
    gaussian: False                   # Gaussian transformation (default: False)
    widths_eV: [0.5, 1.0, 2.0, 4.0]
    basis_stride: 4                  # Value must be consistent with hyperparams/basis_stride
  descriptors:
    - descriptor_type: wacsf
      params:
        r_min: 1.0
        r_max: 6.0
        n_g2: 16
        n_g4: 32

model:
  model_type: mlp
  params:
    hidden_size: 256
    dropout: 0.1
    num_hidden_layers: 3
    shrink_rate: 0.5
    activation: prelu
  weights_init:
    weights: xavier_uniform
    bias: zeros

learner:
  learner_type: nnlearner
  params:
    epochs: 10
    batch_size: 3
    learning_rate: 0.001
    optimizer: Adam
    loss:
      loss_type: mse
    regularizer:
      regularizer_type: none
      
    loss_lambda: 0.001
  
strategy:
  strategy_type: single

lr_scheduler: False
scheduler_params:
  scheduler_type: step
  step_size: 1
  gamma: 0.1


# Other strategies
# // strategy:
# //   type: kfold
# //   params:
# //     n_splits: 2
# //     n_repeats: 1
# //     seed: 2021

# // strategy:
# //   type: bootstrap
# //   params:
# //     n_boot: 3
# //     n_size: 1.0
# //     weight_seed: [97, 39, 22]

# // strategy: 
# //   type: ensemble
# //   params:
# //     n_ens: 3
# //     weight_seed: [97, 39, 22]



