"""
XANESNET

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either Version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program.  If not, see <https://www.gnu.org/licenses/>.
"""

"""
End-to-end parity of ``forward()`` inputs between xanesnet and fairchem.

In xanesnet, all graph indices and basis inputs that the GemNet / GemNet-OC  ``forward`` function consumes 
are produced by ``GemNetDataset.prepare()`` (offline, per sample).  In fairchem they are produced *inside* 
the forward call by ``generate_interaction_graph``, ``get_triplets``, ``get_mixed_triplets`` and ``get_quadruplets``.

This file ports exactly those fairchem in-forward routines and compares their output, end-to-end, 
to what xanesnet serialises into every ``GemNetData`` sample.  
If any of the tensors that the model forward sees does not agree between the two pipelines, these tests fail.

Scope of comparison (as SETS — the two implementations may emit edges in different orders, 
but the set of enumerated edges / triplets / quadruplets must be identical):

1. **Main graph** edges — the ``(src, dst, cell_offset)`` triples enumerated
   by ``build_edges`` must equal a brute-force periodic image enumeration
   at the main cutoff.
2. For **GemNet** (triplets-only) and **GemNet-OC** — id_swap involution,
   compute_triplets output (id3_reduce_ca, id3_expand_ba) against
   ``ref_get_triplets`` on the identical edge set.
3. For **GemNet-OC** only:
   - ``a2ee2a``, ``a2a`` and ``qint`` graphs' edge sets vs brute-force.
   - ``trip_a2e``, ``trip_e2a``, ``trip_e2e`` (mixed triplets) vs
     ``ref_get_mixed_triplets`` on those graphs.
   - Quadruplets ``(id4_reduce_ca, id4_expand_db)`` vs
     ``ref_get_quadruplets``.
   - Per-atom ``target_neighbor_idx`` generated by ``get_inner_idx`` on
     the a2ee2a and a2a target columns.

All of these are value-level checks — any mismatch makes the GemNet / GemNet-OC forward 
pass see different inputs than the fairchem reference would see.
"""

from pathlib import Path

import numpy as np
import pytest
import torch
from pymatgen.core import Molecule, Structure

from xanesnet.datasets.torchgeometric.gemnet import GemNetDataset
from xanesnet.datasources.pmgjson import PMGJSONSource
from xanesnet.datasources.xyzspec import XYZSpecSource
from xanesnet.models.gemnet_oc.utils import get_inner_idx as xn_get_inner_idx

from .conftest import (
    cell_offsets_from_edge_vec,
    ref_get_mixed_triplets,
    ref_get_quadruplets,
    ref_get_triplets,
    reference_periodic_edges,
    sort_triplet_set,
)

pytestmark = pytest.mark.parity


# Helpers


def _edges_from_sample(
    edge_index: torch.Tensor,
    edge_vec: torch.Tensor,
    pos: torch.Tensor,
    lattice: torch.Tensor | None,
) -> set[tuple[int, int, tuple[int, int, int]]]:
    """
    Reduce a xanesnet edge tensor to the canonical ``(src, dst, integer_cell_offset)``
    set used by fairchem / the brute-force reference.
    """
    offsets = cell_offsets_from_edge_vec(edge_index, edge_vec.to(torch.float64), pos.to(torch.float64), lattice)
    return {
        (int(edge_index[0, k]), int(edge_index[1, k]), tuple(offsets[k].tolist())) for k in range(edge_index.size(1))
    }


def _reference_edges(obj, cutoff: float) -> set[tuple[int, int, tuple[int, int, int]]]:
    """
    Unified brute-force neighbour enumeration for Structure OR Molecule.

    For non-periodic inputs every offset is ``(0, 0, 0)``.
    """
    if isinstance(obj, Structure):
        return reference_periodic_edges(obj, cutoff=cutoff, image_range=2)
    # Molecule: pairwise distance check, no images.
    pos = np.asarray(obj.cart_coords, dtype=np.float64)
    n = len(obj)
    out: set[tuple[int, int, tuple[int, int, int]]] = set()
    for i in range(n):
        for j in range(n):
            if i == j:
                continue
            if float(np.linalg.norm(pos[j] - pos[i])) <= cutoff + 1e-6:
                out.add((i, j, (0, 0, 0)))
    return out


def _cell_offsets_from_sample(
    edge_index: torch.Tensor,
    edge_vec: torch.Tensor,
    pos: torch.Tensor,
    lattice: torch.Tensor | None,
) -> torch.Tensor:
    return cell_offsets_from_edge_vec(edge_index, edge_vec.to(torch.float64), pos.to(torch.float64), lattice)


def _lattice_of(obj) -> torch.Tensor | None:
    return torch.tensor(obj.lattice.matrix, dtype=torch.float64) if isinstance(obj, Structure) else None


# Dataset construction


def _mk_periodic_dataset(json_dir: Path, root: Path) -> GemNetDataset:
    src = PMGJSONSource(datasource_type="pmgjson", json_path=str(json_dir))
    return GemNetDataset(
        dataset_type="gemnet",
        datasource=src,
        root=str(root),
        preload=False,
        skip_prepare=False,
        split_ratios=None,
        split_indexfile=None,
        cutoff=3.5,
        max_num_neighbors=50,
        graph_method="radius",
        min_facet_area=None,
        cov_radii_scale=1.5,
        quadruplets=True,
        int_cutoff=4.5,
        oc_mode=True,
        oc_cutoff_aeaint=3.5,
        oc_cutoff_aint=4.5,
        oc_max_neighbors_aeaint=50,
        oc_max_neighbors_aint=50,
    )


def _mk_molecule_dataset(fe_mini: tuple[Path, Path], root: Path) -> GemNetDataset:
    xyz_dir, xanes_dir = fe_mini
    src = XYZSpecSource(
        datasource_type="xyzspec",
        xyz_path=str(xyz_dir),
        xanes_path=str(xanes_dir),
    )
    return GemNetDataset(
        dataset_type="gemnet",
        datasource=src,
        root=str(root),
        preload=False,
        skip_prepare=False,
        split_ratios=None,
        split_indexfile=None,
        cutoff=3.5,
        max_num_neighbors=50,
        graph_method="radius",
        min_facet_area=None,
        cov_radii_scale=1.5,
        quadruplets=True,
        int_cutoff=4.5,
        oc_mode=True,
        oc_cutoff_aeaint=3.5,
        oc_cutoff_aint=4.5,
        oc_max_neighbors_aeaint=50,
        oc_max_neighbors_aint=50,
    )


# Load test objects (paired sample + original pymatgen obj)


@pytest.fixture(scope="module")
def periodic_pairs(omnixas_data_dir, tmp_path_factory):
    """
    Up to 5 periodic samples paired with their pymatgen Structure.
    """
    tmp = tmp_path_factory.mktemp("fip_periodic")
    ds = _mk_periodic_dataset(omnixas_data_dir, tmp)
    ds.prepare()
    pairs: list[tuple[Structure, object]] = []
    for i in range(min(5, len(ds))):
        sample = ds[i]
        stem = sample.file_name
        s = Structure.from_file(str(omnixas_data_dir / f"{stem}.json"))
        pairs.append((s, sample))
    assert len(pairs) >= 3
    return pairs


@pytest.fixture(scope="module")
def molecule_pairs(fe_mini_data, tmp_path_factory):
    """
    Up to 5 molecular samples paired with their pymatgen Molecule.
    """
    tmp = tmp_path_factory.mktemp("fip_molecule")
    ds = _mk_molecule_dataset(fe_mini_data, tmp)
    ds.prepare()
    xyz_dir, _ = fe_mini_data
    pairs: list[tuple[Molecule, object]] = []
    for i in range(min(5, len(ds))):
        sample = ds[i]
        stem = sample.file_name
        m = Molecule.from_file(str(xyz_dir / f"{stem}.xyz"))
        pairs.append((m, sample))
    assert len(pairs) >= 3
    return pairs


# 1. Main-graph edges


def _assert_edge_set_parity(obj, sample, cutoff, edge_index_attr, vec_attr):
    """
    Assert the edges on one graph of a xanesnet sample == brute-force set.
    """
    ei = getattr(sample, edge_index_attr)
    ev = getattr(sample, vec_attr)
    pos = sample.pos
    lat = _lattice_of(obj)
    xn = _edges_from_sample(ei, ev, pos, lat)
    ref = _reference_edges(obj, cutoff)
    assert xn == ref, (
        f"{edge_index_attr} mismatch on {getattr(obj, 'properties', {}).get('file_name', '?')}:"
        f" xn-only={xn - ref}, ref-only={ref - xn}"
    )


def test_main_graph_edges_periodic(periodic_pairs):
    for s, sample in periodic_pairs:
        _assert_edge_set_parity(s, sample, cutoff=3.5, edge_index_attr="edge_index", vec_attr="edge_vec")


def test_main_graph_edges_molecule(molecule_pairs):
    for m, sample in molecule_pairs:
        _assert_edge_set_parity(m, sample, cutoff=3.5, edge_index_attr="edge_index", vec_attr="edge_vec")


# 2. Auxiliary OC graphs (a2ee2a, a2a, qint)


def test_a2ee2a_graph_edges_periodic(periodic_pairs):
    for s, sample in periodic_pairs:
        _assert_edge_set_parity(s, sample, cutoff=3.5, edge_index_attr="a2ee2a_edge_index", vec_attr="a2ee2a_edge_vec")


def test_a2a_graph_edges_periodic(periodic_pairs):
    for s, sample in periodic_pairs:
        _assert_edge_set_parity(s, sample, cutoff=4.5, edge_index_attr="a2a_edge_index", vec_attr="a2a_edge_vec")


def test_qint_graph_edges_periodic(periodic_pairs):
    for s, sample in periodic_pairs:
        _assert_edge_set_parity(s, sample, cutoff=4.5, edge_index_attr="qint_edge_index", vec_attr="qint_edge_vec")


def test_a2ee2a_graph_edges_molecule(molecule_pairs):
    for m, sample in molecule_pairs:
        _assert_edge_set_parity(m, sample, cutoff=3.5, edge_index_attr="a2ee2a_edge_index", vec_attr="a2ee2a_edge_vec")


def test_a2a_graph_edges_molecule(molecule_pairs):
    for m, sample in molecule_pairs:
        _assert_edge_set_parity(m, sample, cutoff=4.5, edge_index_attr="a2a_edge_index", vec_attr="a2a_edge_vec")


# 3. id_swap involution + vector negation (identical to fairchem's ``reorder_symmetric_edges`` post-condition)


def test_id_swap_is_fairchem_compatible_periodic(periodic_pairs):
    for _s, sample in periodic_pairs:
        swap = sample.id_swap
        nE = sample.edge_index.size(1)
        assert swap.size(0) == nE
        assert swap[swap].tolist() == list(range(nE))
        assert torch.allclose(sample.edge_vec[swap], -sample.edge_vec, atol=1e-5)
        # reverse of (s,d) must be (d,s)
        assert torch.equal(sample.edge_index[0, swap], sample.edge_index[1])
        assert torch.equal(sample.edge_index[1, swap], sample.edge_index[0])


def test_id_swap_is_fairchem_compatible_molecule(molecule_pairs):
    for _m, sample in molecule_pairs:
        swap = sample.id_swap
        nE = sample.edge_index.size(1)
        assert swap[swap].tolist() == list(range(nE))
        assert torch.equal(sample.edge_index[0, swap], sample.edge_index[1])


# 4. Main-graph triplets (id3_reduce_ca / id3_expand_ba) vs fairchem


def _triplet_parity(obj, sample):
    ei = sample.edge_index
    n = sample.pos.size(0)
    ref = ref_get_triplets(ei, num_atoms=n)
    xn = sort_triplet_set(sample.id3_expand_ba, sample.id3_reduce_ca)
    rf = sort_triplet_set(ref["in"], ref["out"])
    assert xn == rf


def test_main_triplets_periodic(periodic_pairs):
    for s, sample in periodic_pairs:
        _triplet_parity(s, sample)


def test_main_triplets_molecule(molecule_pairs):
    for m, sample in molecule_pairs:
        _triplet_parity(m, sample)


# 5. Mixed triplets (trip_a2e / trip_e2a / trip_e2e) vs fairchem


def _graph_dict(edge_index, edge_vec, pos, lat) -> dict[str, torch.Tensor]:
    offsets = cell_offsets_from_edge_vec(edge_index, edge_vec.to(torch.float64), pos.to(torch.float64), lat)
    return {"edge_index": edge_index, "cell_offset": offsets}


def _mixed_triplet_parity(obj, sample):
    lat = _lattice_of(obj)
    pos = sample.pos
    main = _graph_dict(sample.edge_index, sample.edge_vec, pos, lat)
    a2e = _graph_dict(sample.a2ee2a_edge_index, sample.a2ee2a_edge_vec, pos, lat)
    n = pos.size(0)

    # trip_a2e: xanesnet computes this as
    #   compute_mixed_triplets(main=main_edge_index, other=a2ee2a_edge_index, to_outedge=False)
    # which iterates main edges c->a and pulls a2ee2a edges (b->c) into the
    # source of the main edge.  Fairchem equivalent:
    #   get_mixed_triplets(graph_in=a2ee2a, graph_out=main, to_outedge=False)
    ref_a2e = ref_get_mixed_triplets(a2e, main, num_atoms=n, to_outedge=False)
    xn_a2e = sort_triplet_set(sample.trip_a2e_in, sample.trip_a2e_out)
    rf_a2e = sort_triplet_set(ref_a2e["in"], ref_a2e["out"])
    assert xn_a2e == rf_a2e, "trip_a2e mismatch"

    # trip_e2a: iterate a2ee2a edges (c->a), pull main edges feeding a.
    ref_e2a = ref_get_mixed_triplets(main, a2e, num_atoms=n, to_outedge=False)
    xn_e2a = sort_triplet_set(sample.trip_e2a_in, sample.trip_e2a_out)
    rf_e2a = sort_triplet_set(ref_e2a["in"], ref_e2a["out"])
    assert xn_e2a == rf_e2a, "trip_e2a mismatch"

    # trip_e2e: iterate main edges (c->a), pull main edges feeding a.
    ref_e2e = ref_get_mixed_triplets(main, main, num_atoms=n, to_outedge=False)
    xn_e2e = sort_triplet_set(sample.trip_e2e_in, sample.trip_e2e_out)
    rf_e2e = sort_triplet_set(ref_e2e["in"], ref_e2e["out"])
    assert xn_e2e == rf_e2e, "trip_e2e mismatch"


def test_mixed_triplets_periodic(periodic_pairs):
    for s, sample in periodic_pairs:
        _mixed_triplet_parity(s, sample)


def test_mixed_triplets_molecule(molecule_pairs):
    for m, sample in molecule_pairs:
        _mixed_triplet_parity(m, sample)


# 6. Quadruplets (id4_reduce_ca / id4_expand_db) vs fairchem


def _quadruplet_parity(obj, sample):
    lat = _lattice_of(obj)
    pos = sample.pos
    main = _graph_dict(sample.edge_index, sample.edge_vec, pos, lat)
    qint = _graph_dict(sample.qint_edge_index, sample.qint_edge_vec, pos, lat)
    ref = ref_get_quadruplets(main, qint, num_atoms=pos.size(0))
    xn_pairs = sorted(zip(sample.id4_reduce_ca.tolist(), sample.id4_expand_db.tolist()))
    rf_pairs = sorted(zip(ref["out"].tolist(), ref["in_db"].tolist()))
    assert xn_pairs == rf_pairs, "quadruplet pair set mismatch"


def test_quadruplets_periodic(periodic_pairs):
    for s, sample in periodic_pairs:
        _quadruplet_parity(s, sample)


def test_quadruplets_molecule(molecule_pairs):
    for m, sample in molecule_pairs:
        _quadruplet_parity(m, sample)


# 7. target_neighbor_idx from get_inner_idx — what gemnet_oc.forward computes live on the a2ee2a / a2a target columns.


def _ref_inner_idx(idx: torch.Tensor, dim_size: int) -> torch.Tensor:
    """
    Reference implementation: for each element, count how many prior elements share the same idx value.
    Matches fairchem's ``segment_coo`` semantics on sorted input AND xanesnet's ``get_inner_idx`` in general.
    """
    n = idx.size(0)
    result = torch.empty(n, dtype=torch.int64)
    counts = [0] * dim_size
    # We need a version that is consistent with how the production code
    # groups edges — the simplest common denominator is to sort by idx,
    # assign 0..K-1 per group, and scatter back. That's exactly what
    # xanesnet's get_inner_idx does.
    sort = torch.argsort(idx, stable=True)
    seen = [0] * dim_size
    for rank in range(n):
        orig = int(sort[rank].item())
        g = int(idx[orig].item())
        result[orig] = seen[g]
        seen[g] += 1
    return result


def test_target_neighbor_idx_periodic(periodic_pairs):
    for _s, sample in periodic_pairs:
        n = sample.pos.size(0)
        for attr in ("a2ee2a_edge_index", "a2a_edge_index"):
            ei = getattr(sample, attr)
            out = xn_get_inner_idx(ei[1], dim_size=n)
            ref = _ref_inner_idx(ei[1], n)
            assert torch.equal(out, ref), f"{attr} inner-idx mismatch"


def test_target_neighbor_idx_molecule(molecule_pairs):
    for _m, sample in molecule_pairs:
        n = sample.pos.size(0)
        for attr in ("a2ee2a_edge_index", "a2a_edge_index"):
            ei = getattr(sample, attr)
            out = xn_get_inner_idx(ei[1], dim_size=n)
            ref = _ref_inner_idx(ei[1], n)
            assert torch.equal(out, ref)


# 8. Distance / direction vector consistency (fairchem computes these inside generate_interaction_graph).


def test_distances_equal_vector_norm_periodic(periodic_pairs):
    for _s, sample in periodic_pairs:
        for ew_attr, ev_attr in [
            ("edge_weight", "edge_vec"),
            ("a2ee2a_edge_weight", "a2ee2a_edge_vec"),
            ("a2a_edge_weight", "a2a_edge_vec"),
            ("qint_edge_weight", "qint_edge_vec"),
        ]:
            ew = getattr(sample, ew_attr)
            ev = getattr(sample, ev_attr)
            assert torch.allclose(ew, torch.linalg.norm(ev, dim=-1), atol=1e-5)


def test_distances_equal_vector_norm_molecule(molecule_pairs):
    for _m, sample in molecule_pairs:
        for ew_attr, ev_attr in [
            ("edge_weight", "edge_vec"),
            ("a2ee2a_edge_weight", "a2ee2a_edge_vec"),
            ("a2a_edge_weight", "a2a_edge_vec"),
        ]:
            ew = getattr(sample, ew_attr)
            ev = getattr(sample, ev_attr)
            assert torch.allclose(ew, torch.linalg.norm(ev, dim=-1), atol=1e-5)
