seed: 2025
device: cuda

datasource:
  datasource_type: xyzspec
  xyz_path: .github/workflows/data/fe/xyz_train
  xanes_path: .github/workflows/data/fe/xanes_train

dataset:
  root: .github/workflows/data/fe/processed_train
  preload: True                    # Preload dataset into RAM if True; otherwise load on-the-fly

inferencer:
  inferencer_type: nninferencer
  params:
    batch_size: 3