name: Test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        env:
          CXXFLAGS: '-ftemplate-depth=2048'
        run: |
          python3 -m pip install --upgrade pip
          python -m pip install .

      - name: MLP (STD)
        run: |
          echo "--- Running: MLP (STD) XYZ -> XANES ---"
          sed -i 's/gaussian: False/gaussian: True/' ./.github/workflows/inputs/in_mlp.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/mlp_std_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/gaussian: True/gaussian: False/' ./.github/workflows/inputs/in_mlp.yaml
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: MLP (STD) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xyz --in_model models/mlp_std_xanes_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: MLP (Kfold)
        run: |
          echo "--- Running: MLP (Kfold) XYZ -> XANES ---"
          sed -i 's/kfold: False/kfold: True/' ./.github/workflows/inputs/in_mlp.yaml
          sed -i 's/gaussian: False/gaussian: True/' ./.github/workflows/inputs/in_mlp.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/mlp_kfold_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/gaussian: True/gaussian: False/' ./.github/workflows/inputs/in_mlp.yaml
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: MLP (Kfold) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xyz --in_model models/mlp_kfold_xanes_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/kfold: True/kfold: False/' ./.github/workflows/inputs/in_mlp.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: MLP (Bootstrap)
        run: |
          echo "--- Running: MLP (Bootstrap) XYZ -> XANES ---"
          sed -i 's/bootstrap: False/bootstrap: True/' ./.github/workflows/inputs/in_mlp.yaml
          sed -i 's/gaussian: False/gaussian: True/' ./.github/workflows/inputs/in_mlp.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/mlp_bootstrap_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/gaussian: True/gaussian: False/' ./.github/workflows/inputs/in_mlp.yaml
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: MLP (Bootstrap) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xyz --in_model models/mlp_bootstrap_xanes_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/bootstrap: True/bootstrap: False/' ./.github/workflows/inputs/in_mlp.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: MLP (Ensemble)
        run: |    
          echo "--- Running: MLP (Ensemble) XYZ -> XANES ---"
          sed -i 's/ensemble: False/ensemble: True/' ./.github/workflows/inputs/in_mlp.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/mlp_ensemble_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: MLP (Ensemble) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xyz --in_model models/mlp_ensemble_xanes_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/ensemble: True/ensemble: False/' ./.github/workflows/inputs/in_mlp.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: CNN (STD)
        run: |
          echo "--- Running: CNN (STD) XYZ -> XANES ---"
          sed -i 's/gaussian: False/gaussian: True/' ./.github/workflows/inputs/in_cnn.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_cnn.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/cnn_std_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/gaussian: True/gaussian: False/' ./.github/workflows/inputs/in_cnn.yaml
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: CNN (STD) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_cnn.yaml --save
          python3 -m xanesnet.cli --mode predict_xyz --in_model models/cnn_std_xanes_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: LSTM (STD)
        run: |
          echo "--- Running: LSTM (STD) XYZ -> XANES ---"
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_lstm.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/lstm_std_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: LSTM (STD) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_lstm.yaml --save
          python3 -m xanesnet.cli --mode predict_xyz --in_model models/lstm_std_xanes_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: AE_MLP (STD)
        run: |
          echo "--- Running: AE_MLP (STD) XYZ -> XANES ---"
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_ae_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/ae_mlp_std_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: AE_MLP (STD) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_ae_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xyz --in_model models/ae_mlp_std_xanes_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: AE_MLP (Kfold)
        run: |
          echo "--- Running: AE_MLP (Kfold) XYZ -> XANES ---"
          sed -i 's/kfold: False/kfold: True/' ./.github/workflows/inputs/in_ae_mlp.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_ae_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/ae_mlp_kfold_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: AE_MLP (Kfold) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_ae_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xyz --in_model models/ae_mlp_kfold_xanes_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/kfold: True/kfold: False/' ./.github/workflows/inputs/in_ae_mlp.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: AE_MLP (Bootstrap)
        run: |
          echo "--- Running: AE_MLP (Bootstrap) XYZ -> XANES ---"
          sed -i 's/bootstrap: False/bootstrap: True/' ./.github/workflows/inputs/in_ae_mlp.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_ae_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/ae_mlp_bootstrap_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: AE_MLP (Bootstrap) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_ae_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xyz --in_model models/ae_mlp_bootstrap_xanes_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/bootstrap: True/bootstrap: False/' ./.github/workflows/inputs/in_ae_mlp.yaml
          rm -rf ./.github/workflows/data/fe/processed*


      - name: AE_MLP (Ensemble)
        run: |    
          sed -i 's/ensemble: False/ensemble: True/' ./.github/workflows/inputs/in_ae_mlp.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_ae_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/ae_mlp_ensemble_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: AE_MLP (Ensemble) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_ae_mlp.yaml --save
          python3 -m xanesnet.cli --mode predict_xyz --in_model models/ae_mlp_ensemble_xanes_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/ensemble: True/ensemble: False/' ./.github/workflows/inputs/in_ae_mlp.yaml
          rm -rf ./.github/workflows/data/fe/processed*


      - name: AE_CNN (STD)
        run: |
          echo "--- Running: AE_CNN (STD) XYZ -> XANES ---"
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_ae_cnn.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/ae_cnn_std_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: AE_CNN (STD) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_ae_cnn.yaml --save
          python3 -m xanesnet.cli --mode predict_xyz --in_model models/ae_cnn_std_xanes_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*


      - name: AEGAN (STD)
        run: |
          echo "--- Running: AEGAN (STD) ---"
          python3 -m xanesnet.cli --mode train_all --in_file ./.github/workflows/inputs/in_aegan.yaml --save
          python3 -m xanesnet.cli --mode predict_all --in_model models/aegan_mlp_std_all_001 --in_file ./.github/workflows/inputs/in_predict.yaml

      - name: AEGAN (Kfold)
        run: |
          echo "--- Running: AEGAN (Kfold) ---"
          sed -i 's/kfold: False/kfold: True/' ./.github/workflows/inputs/in_aegan.yaml
          python3 -m xanesnet.cli --mode train_all --in_file ./.github/workflows/inputs/in_aegan.yaml --save
          python3 -m xanesnet.cli --mode predict_all --in_model models/aegan_mlp_kfold_all_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/kfold: True/kfold: False/' ./.github/workflows/inputs/in_aegan.yaml

      - name: AEGAN (Bootstrap)
        run: |
          echo "--- Running: AEGAN (Bootstrap) ---"
          sed -i 's/bootstrap: False/bootstrap: True/' ./.github/workflows/inputs/in_aegan.yaml
          python3 -m xanesnet.cli --mode train_all --in_file ./.github/workflows/inputs/in_aegan.yaml --save
          python3 -m xanesnet.cli --mode predict_all --in_model models/aegan_mlp_bootstrap_all_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/bootstrap: True/bootstrap: False/' ./.github/workflows/inputs/in_aegan.yaml

      - name: AEGAN (Ensemble)
        run: |    
          sed -i 's/ensemble: False/ensemble: True/' ./.github/workflows/inputs/in_aegan.yaml
          python3 -m xanesnet.cli --mode train_all --in_file ./.github/workflows/inputs/in_aegan.yaml --save
          python3 -m xanesnet.cli --mode predict_all --in_model models/aegan_mlp_ensemble_all_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/ensemble: True/ensemble: False/' ./.github/workflows/inputs/in_aegan.yaml
          rm -rf ./.github/workflows/data/fe/processed*


      - name: GNN (Std)
        run: |
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_gnn.yaml  --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/gnn_std_xyz_001 --in_file ./.github/workflows/inputs/in_predict_gnn.yaml

      - name: GNN (Kfold)
        run: |
          sed -i 's/kfold: False/kfold: True/' ./.github/workflows/inputs/in_gnn.yaml 
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_gnn.yaml  --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/gnn_kfold_xyz_001 --in_file ./.github/workflows/inputs/in_predict_gnn.yaml
          sed -i 's/kfold: True/kfold: False/' ./.github/workflows/inputs/in_gnn.yaml

      - name: GNN (Bootstrap)
        run: |
          sed -i 's/bootstrap: False/bootstrap: True/' ./.github/workflows/inputs/in_gnn.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_gnn.yaml  --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/gnn_bootstrap_xyz_001 --in_file ./.github/workflows/inputs/in_predict_gnn.yaml
          # disable boostrap
          sed -i 's/bootstrap: True/bootstrap: False/' ./.github/workflows/inputs/in_gnn.yaml

      - name: GNN (Ensemble)
        run: |    
          # enable ensemble
          sed -i 's/ensemble: False/ensemble: True/' ./.github/workflows/inputs/in_gnn.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_gnn.yaml  --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/gnn_ensemble_xyz_001 --in_file ./.github/workflows/inputs/in_predict_gnn.yaml
          rm -rf ./.github/workflows/data/graph-set/processed*
          sed -i 's/ensemble: True/ensemble: False/' ./.github/workflows/inputs/in_gnn.yaml

      - name: Transformer (Std)
        run: |
          echo "--- Running: Transformer (STD) ---"
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_transformer.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/transformer_std_xyz_001 --in_file ./.github/workflows/inputs/in_predict_gnn.yaml

      - name: Transformer (Kfold)
        run: |
          echo "--- Running: Transformer (Kfold) ---"
          sed -i 's/kfold: False/kfold: True/' ./.github/workflows/inputs/in_transformer.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_transformer.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/transformer_kfold_xyz_001 --in_file ./.github/workflows/inputs/in_predict_gnn.yaml
          sed -i 's/kfold: True/kfold: False/' ./.github/workflows/inputs/in_transformer.yaml
          

      - name: Transformer (Bootstrap)
        run: |
          echo "--- Running: Transformer (Bootstrap) ---"
          sed -i 's/bootstrap: False/bootstrap: True/' ./.github/workflows/inputs/in_transformer.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_transformer.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/transformer_bootstrap_xyz_001 --in_file ./.github/workflows/inputs/in_predict_gnn.yaml
          sed -i 's/bootstrap: True/bootstrap: False/' ./.github/workflows/inputs/in_transformer.yaml

      - name: Transformer (Bootstrap)
        run: |
          echo "--- Running: Transformer (Ensemble) ---"
          sed -i 's/ensemble: False/ensemble: True/' ./.github/workflows/inputs/in_transformer.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_transformer.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/transformer_ensemble_xyz_001 --in_file ./.github/workflows/inputs/in_predict_gnn.yaml
          sed -i 's/ensemble: True/ensemble: False/' ./.github/workflows/inputs/in_transformer.yaml
          rm -rf ./.github/workflows/data/graph-set/processed*

      - name: MultiHead-MLP (STD)
        run: |
          echo "--- Running: MH-MLP (STD) XYZ -> XANES ---"
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_mh_mlp.yaml --save
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: MH-MLP (STD) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_mh_mlp.yaml --save
          rm -rf ./.github/workflows/data/fe/processed*

      - name: MultiHead-MLP (Kfold)
        run: |
          echo "--- Running: MH-MLP (Kfold) XYZ -> XANES ---"
          sed -i 's/kfold: False/kfold: True/' ./.github/workflows/inputs/in_mh_mlp.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_mh_mlp.yaml --save
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: MH-MLP (Kfold) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_mh_mlp.yaml --save
          sed -i 's/kfold: True/kfold: False/' ./.github/workflows/inputs/in_mh_mlp.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: MultiHead-MLP (Bootstrap)
        run: |
          echo "--- Running: MH-MLP (Bootstrap) XYZ -> XANES ---"
          sed -i 's/bootstrap: False/bootstrap: True/' ./.github/workflows/inputs/in_mh_mlp.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_mh_mlp.yaml --save
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: MLP (Bootstrap) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_mh_mlp.yaml --save
          sed -i 's/bootstrap: True/bootstrap: False/' ./.github/workflows/inputs/in_mh_mlp.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: MultiHead-MLP (Ensemble)
        run: |
          echo "--- Running: MH-MLP (Ensemble) XYZ -> XANES ---"
          sed -i 's/ensemble: False/ensemble: True/' ./.github/workflows/inputs/in_mh_mlp.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_mh_mlp.yaml --save
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: MLP (Ensemble) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_mh_mlp.yaml --save
          sed -i 's/ensemble: True/ensemble: False/' ./.github/workflows/inputs/in_mh_mlp.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: MultiHead-CNN (STD)
        run: |
          echo "--- Running: MH-CNN (STD) XYZ -> XANES ---"
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_mh_cnn.yaml --save
          #python3 -m xanesnet.cli --mode predict_xanes --in_model models/mh_cnn_std_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*
          echo "--- Running: MH-CNN (STD) XANES -> XYZ ---"
          python3 -m xanesnet.cli --mode train_xanes --in_file ./.github/workflows/inputs/in_mh_cnn.yaml --save
          #python3 -m xanesnet.cli --mode predict_xyz --in_model models/mh_cnn_std_xanes_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: SoftShell (STD)
        run: |
          echo "--- Running: SoftShell (STD) XYZ -> XANES ---"
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_softshell.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/softshell_std_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: SoftShell (Kfold)
        run: |
          echo "--- Running: SoftShell (Kfold) XYZ -> XANES ---"
          sed -i 's/kfold: False/kfold: True/' ./.github/workflows/inputs/in_softshell.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_softshell.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/softshell_kfold_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/kfold: True/kfold: False/' ./.github/workflows/inputs/in_softshell.yaml
          rm -rf ./.github/workflows/data/fe/processed*
                

      - name: SoftShell (Bootstrap)
        run: |
          echo "--- Running: SoftShell (Bootstrap) XYZ -> XANES ---"
          sed -i 's/bootstrap: False/bootstrap: True/' ./.github/workflows/inputs/in_softshell.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_softshell.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/softshell_bootstrap_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/bootstrap: True/bootstrap: False/' ./.github/workflows/inputs/in_softshell.yaml
          rm -rf ./.github/workflows/data/fe/processed*

      - name: SoftShell (STD)
        run: |
          echo "--- Running: SoftShell (Ensemble) ---"
          sed -i 's/ensemble: False/ensemble: True/' ./.github/workflows/inputs/in_softshell.yaml
          python3 -m xanesnet.cli --mode train_xyz --in_file ./.github/workflows/inputs/in_softshell.yaml --save
          python3 -m xanesnet.cli --mode predict_xanes --in_model models/softshell_ensemble_xyz_001 --in_file ./.github/workflows/inputs/in_predict.yaml
          sed -i 's/ensemble: True/ensemble: False/' ./.github/workflows/inputs/in_softshell.yaml
          rm -rf ./.github/workflows/data/graph-set/processed*
          

#      - name: Run unit tests
#        run: pytest
